version: "2"
services:
  zookeeper:
    image: cdc/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: cdc/kafka
    depends_on:
      - zookeeper
    links:
      - "zookeeper:zookeeper"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - "9092:9092"
  schema-registry:
    image: cdc/schema-registry
    depends_on:
      - zookeeper
      - kafka
    links:
      - "zookeeper:zookeeper"
      - "kafka:kafka"
    environment:
      SR_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
    ports:
      - "8081:8081"
  rest-proxy:
    image: cdc/rest-proxy
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    links:
      - "zookeeper:zookeeper"
      - "kafka:kafka"
      - "schema-registry:schema-registry"
    environment:
      RP_ZOOKEEPER_CONNECT: "zookeeper:2181"
      RP_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
    ports:
      - "8082:8082"

